# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9c6hV5wIPtddCXNpwG14a0nunPPEKLr
"""



import numpy as np

class Polynomial:
    def __init__(self, coeffs):
        self.coeffs = coeffs

    def __repr__(self):
        return " + ".join(f"{c}x^{i}" if c != 0 else "" for i, c in enumerate(self.coeffs) if c != 0)

    def __add__(self, other):
        result = [0] * max(len(self.coeffs), len(other.coeffs))
        for i in range(len(self.coeffs)):
            result[i] += self.coeffs[i]
        for i in range(len(other.coeffs)):
            result[i] += other.coeffs[i]
        return Polynomial(result)

    def __mul__(self, other):
        result = [0] * (len(self.coeffs) + len(other.coeffs) - 1)
        for i, c1 in enumerate(self.coeffs):
            for j, c2 in enumerate(other.coeffs):
                result[i + j] += c1 * c2
        return Polynomial(result)

    def mod(self, mod_poly):
        result_coeffs = self.coeffs[:]
        while len(result_coeffs) >= len(mod_poly.coeffs):
            if result_coeffs[-1] != 0:
                degree_diff = len(result_coeffs) - len(mod_poly.coeffs)
                for i in range(len(mod_poly.coeffs)):
                    result_coeffs[degree_diff + i] -= mod_poly.coeffs[i]
            result_coeffs.pop()
        return Polynomial(result_coeffs)

class Module:
    def __init__(self, matrix):
        self.matrix = [[Polynomial(coeffs) if isinstance(coeffs, list) else coeffs for coeffs in row] for row in matrix]

    def __matmul__(self, other):
        result = []
        for i in range(len(self.matrix)):
            row_result = []
            for j in range(len(other.matrix[0])):
                polynomial_sum = Polynomial([0] * len(self.matrix[0][0].coeffs))
                for k in range(len(self.matrix[0])):
                    polynomial_sum += self.matrix[i][k] * other.matrix[k][j]
                row_result.append(polynomial_sum)
            result.append(row_result)
        return Module(result)

    def __add__(self, other):
        result = []
        for i in range(len(self.matrix)):
            row_result = []
            for j in range(len(self.matrix[i])):
                row_result.append(self.matrix[i][j] + other.matrix[i][j])
            result.append(row_result)
        return Module(result)

    def __repr__(self):
        return str(self.matrix)

q = 17
polymax = 4

s0 = Polynomial([0, 1, -1, 1])
s1 = Polynomial([0, 1, 0, 1])

s = Module([[s0.coeffs], [s1.coeffs]])

print("Private key s:")
print(s)
print()

A00 = Polynomial([13, 6, 16, 6])
A01 = Polynomial([4, 5, 8, 0])
A10 = Polynomial([4, 2, 8, 9])
A11 = Polynomial([10, 0, 5, 0])

A = Module([[A00.coeffs, A01.coeffs], [A10.coeffs, A11.coeffs]])

print("Public key matrix A:")
print(A)
print()

e0 = Polynomial([1, 0, 1, 0])
e1 = Polynomial([-1, 1, 0, 0])
e = Module([[e0.coeffs], [e1.coeffs]])

print("Error polynomial e:")
print(e)
print()

A_s = A @ s

t = A_s + e

print("Computed t = A * s + e:")
print(t)
print()

print("Final Public Key (A, t):")
print("A:")
print(A)
print()
print("t:")
print(t)